#!/usr/bin/env bash
#  Bash script to install nginx and configure it to listen on port 80

# Install Nginx and allow it to listen on port 80
sudo apt-get update
sudo apt-get install nginx -y 

# Configure to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Write Hello World! into a file named index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload Nginx
sudo service nginx restart
