#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely and I am invincible!!! when a SIGTERM is received
while 'true'
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I am invincible!!!" SIGTERM
done
