#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd using the while loop + IFS
FILENAME="/etc/passwd"
while IFS=: read -r username password userid groupid useridinfo homedir cmdshell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < $FILENAME
