#!/usr/bin/env bash
# This script is displaying "bad luck" on iteration 4 and "good luck"
# on iteration 8 and  "Best School" on the rest iterations
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
