#!/usr/bin/env bash
# Installs and sets up ufw firewall

sudo apt-get -y update
sudo apt-get install ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw status
sudo ufw reload
