#!/usr/bin/env bash
# This script configures your server for localhost and facebook
# sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts
# echo "8.8.8.8 facebook.com" >> /etc/hosts

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
