#!/usr/bin/env bash
# Ngix configuration that serves the page from the route `/airbnb-onepage/`
 
server {
    listen 80;
    server_name 52.87.216.79;

    location /airbnb-onepage/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /airbnb-dynamic/number_odd_or_even/ {
        proxy_pass http://127.0.0.1:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 404;
    }
}

