#!/usr/bin/env bash
# Default server ngix
server {
    listen 80;
    server_name 52.87.216.79;

    location /api/ {
        proxy_pass http://127.0.0.1:5002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        return 404;
    }
}

