#!/bin/bash

# Specify the server's IP address or hostname
server="8.8.8.8"

# Use ssh with single-character flags to connect to the server
ssh -i~/.ssh/school -oUser=ubuntu $server << EOF
  # Commands to run on the server after connecting
  # For example, 'exit' to close the connection
  exit
EOF

